name: chaos_club
description: ChaosClub - A gamified digital clubhouse for friend groups.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ðŸ”¥ Navigation
  salomon_bottom_bar: ^3.3.2
  http: ^1.1.0
  dio: ^5.4.0  
  shared_preferences: ^2.2.2
  provider: ^6.1.1 
  intl: ^0.18.1
  image_picker: ^1.0.7
  flutter_secure_storage: ^9.0.0
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  cached_network_image: ^3.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # Add logo if you have it
    # - assets/images/logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700